app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='midi.index'),
    path('midi/<int:pk>/', views.view, name='midi.view'),
]

midihub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('midi.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Midi(models.Model):
    DIFFICULTY_VERY_EASY = 0
    DIFFICULTY_EASY = 1
    DIFFICULTY_NORMAL = 2
    DIFFICULTY_HARD = 3
    DIFFICULTY_VERY_HARD = 4
    DIFFICULTIES = (
        (DIFFICULTY_VERY_EASY, _('Very easy')),
        (DIFFICULTY_EASY, _('Easy')),
        (DIFFICULTY_NORMAL, _('Normal')),
        (DIFFICULTY_HARD, _('Hard')),
        (DIFFICULTY_VERY_HARD, _('Very hard')),
    )

    title = models.CharField(_('Title'), max_length=255)
    description = models.TextField(_('Description'), blank=True)
    file = models.FileField(_('File'), upload_to='files/midi')
    image = models.ImageField(_('Image'), upload_to='images/midi')
    difficulty = models.PositiveSmallIntegerField(_('Difficulty'), choices=DIFFICULTIES, default=DIFFICULTY_NORMAL)
    created_at = models.DateTimeField(_('Created at'), auto_now_add=True)
    updated_at = models.DateTimeField(_('Updated at'), auto_now=True)

    class Meta:
        verbose_name = _('MIDI file')
        verbose_name_plural = _('MIDI files')
        ordering = ['-created_at']

    def __str__(self):
        return self.title

    def __repr__(self):
        return f'Midi(pk={self.pk}, title={self.title})'

app/views.py
from django.shortcuts import render, get_object_or_404

from app.models import Midi


def index(request):
    midi = Midi.objects.all()[:10]

    return render(request, 'app/index.html', {
        'midi': midi,
    })


def view(request, pk):
    midi = get_object_or_404(Midi, pk=pk)

    return render(request, 'app/view.html', {
        'midi': midi,
    })

midi/views.py
from django.shortcuts import render, get_object_or_404

from midi.models import Midi


def index(request):
    midi = Midi.objects.all()[:10]

    return render(request, 'midi/index.html', {
        'midi': midi,
    })


def view(request, pk):
    midi = get_object_or_404(Midi, pk=pk)

    return render(request, 'midi/view.html', {
        'midi': midi,
    })

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>MidiHub</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% include 'app/includes/navbar.html' %}

{% block content %}{% endblock %}

<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
  </div>
</footer>

</body>
</html>

app/templates/app/includes/hero.html
<section class="hero is-medium is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Hero title
      </h1>
      <h2 class="subtitle">
        Hero subtitle
      </h2>
    </div>
  </div>
  <div class="hero-foot">
    <div class="container is-centered">
      <span>Play</span>
      <span>Detail</span>
    </div>
  </div>
</section>

app/templates/app/includes/menu.html
<aside class="menu">
  <p class="menu-label">Midi</p>
  <ul class="menu-list">
    <li><a href="#">Popular</a></li>
    <li><a href="#">Newest</a></li>
  </ul>
</aside>

app/templates/app/includes/navbar.html
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="https://bulma.io">
        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
      </a>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
         data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a href="{% url 'midi.index' %}" class="navbar-item">Home</a>
{#        <a class="navbar-item">Documentation</a>#}
{#        <div class="navbar-item has-dropdown is-hoverable"><a class="navbar-link">More</a>#}
{#          <div class="navbar-dropdown">#}
{#            <a class="navbar-item">About</a>#}
{#            <a class="navbar-item">Jobs</a>#}
{#            <a class="navbar-item">Contact</a>#}
{#            <hr class="navbar-divider">#}
{#            <a class="navbar-item">Report an issue</a>#}
{#          </div>#}
{#        </div>#}
      </div>
{#      <div class="navbar-end">#}
{#        <div class="navbar-item">#}
{#          <div class="buttons">#}
{#            <a class="button is-primary">#}
{#              <strong>Sign up</strong>#}
{#            </a>#}
{#            <a class="button is-light">Log in</a>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
    </div>
  </div>
</nav>

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}
  {#  {% include 'midi/includes/hero.html' %}#}

  <div class="section">
    <div class="container">
      <div class="columns">
        <div class="column is-one-quarter">
          {% include 'app/includes/menu.html' %}
        </div>
        <div class="column">
          <h1 class="title">Popular MIDI</h1>
          <div class="columns is-multiline">
            {% for item in midi %}
              <div class="column is-4">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-4by3">
                    <img src="{{ item.image.url }}" alt="{{ item.title }} image">
                  </figure>
                </div>
                <div class="card-content">
                  <p class="title is-4">{{ item.title }}</p>
                  <div class="content">
                    <p>{{ item.description }}</p>
                    <span class="tag is-success is-light">{{ item.get_difficulty_display }}</span>
                  </div>
                </div>
                <footer class="card-footer">
                  <a href="#" class="card-footer-item">Play</a>
                  <a href="{% url 'midi.view' item.pk %}" class="card-footer-item">Detail</a>
                </footer>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/app/view.html
{% extends 'app/base.html' %}

{% block content %}
  <div class="section">
    <div class="container">
      <h1 class="title">{{ midi.title }}</h1>
      <div class="columns">
        <div class="column is-three-fifths">
          <figure class="image is-4by3">
            <img src="{{ midi.image.url }}" alt="{{ midi.title }} image">
          </figure>
        </div>
        <div class="column">
          <a href="{{ midi.file.url }}" class="button">Download</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/midi/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>MidiHub</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% include 'midi/includes/navbar.html' %}

{% block content %}{% endblock %}

<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
    </p>
  </div>
</footer>

</body>
</html>

app/templates/midi/index.html
{% extends 'midi/base.html' %}

{% block content %}
  {#  {% include 'midi/includes/hero.html' %}#}

  <div class="section">
    <div class="container">
      <div class="columns">
        <div class="column is-one-quarter">
          {% include 'midi/includes/menu.html' %}
        </div>
        <div class="column">
          <h1 class="title">Popular MIDI</h1>
          <div class="columns is-multiline">
            {% for item in midi %}
              <div class="column is-4">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-4by3">
                    <img src="{{ item.image.url }}" alt="{{ item.title }} image">
                  </figure>
                </div>
                <div class="card-content">
                  <p class="title is-4">{{ item.title }}</p>
                  <div class="content">
                    <p>{{ item.description }}</p>
                    <span class="tag is-success is-light">{{ item.get_difficulty_display }}</span>
                  </div>
                </div>
                <footer class="card-footer">
                  <a href="#" class="card-footer-item">Play</a>
                  <a href="{% url 'midi.view' item.pk %}" class="card-footer-item">Detail</a>
                </footer>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/midi/view.html
{% extends 'midi/base.html' %}

{% block content %}
  <div class="section">
    <div class="container">
      <h1 class="title">{{ midi.title }}</h1>
      <div class="columns">
        <div class="column is-three-fifths">
          <figure class="image is-4by3">
            <img src="{{ midi.image.url }}" alt="{{ midi.title }} image">
          </figure>
        </div>
        <div class="column">
          <a href="{{ midi.file.url }}" class="button">Download</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}